---
# handlers file for ansible-role-nginx
- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: true

- name: validate nginx
  command: nginx -t
  changed_when: false # false thì nó ko chạy tiếp

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart nginx
  systemd:
    name: nginx
    state: restarted 
    