---
# vars file for ansible-role-nginx

# --- Proxy ---
nginx_upstreams_web: |
  server 10.30.7.47:8080 weight=1 max_fails=2 fail_timeout=20s;

nginx_upstreams_keepalive: "128"

nginx_proxy_header: |
  proxy_http_version 1.1;
  proxy_redirect off;
  proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

nginx_servername_proxy_primary: "trongtest.com www.trongtest.com"
nginx_proxy_listen_port_http: "80"
nginx_proxy_listen_port_https: "443"