---
- name: Delete nginx site enable and avalable
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Backup nginx.conf
  command: 
    cmd: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

- name: Delete nginx.conf
  file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: Copy new nginx.conf
  copy:
    src: /home/server/Ansible/Final_lab/vhost/nginx.conf
    dest: /etc/nginx/

- name: Copy configs for 2 block of servers
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/
  with_items:
    - /home/server/Ansible/Final_lab/vhost/hello.example.com.conf
    - /home/server/Ansible/Final_lab/vhost/info.example.com.conf

- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/www/html/info.example.com
    - /var/www/html/hello.example.com

- name: Copy info web page
  copy:
    src: /home/server/Ansible/Final_lab/vhost/info.php
    dest: /var/www/html/info.example.com/

- name: Copy hello world web page
  copy:
    src: /home/server/Ansible/Final_lab/vhost/helloworld.html
    dest: /var/www/html/hello.example.com/
  notify: restart nginx
